### ISSUE TITLE
Invalid data type in config basiccart.settings, found in filemodules/basiccart/config/install/basiccart.settings.yml : Unable to parse at line 24 (near "use_cart_table:0")

### ISSUE THREAD

**Issue by alexdicianu** [unimitysolutionspvtltd/basiccart#3]
Trying to enable the module yielded the following error.

```
$ drush en basiccart
The following extensions will be enabled: basiccart, telephone
Do you really want to continue? (y/n): y
exception 'Drupal\Core\Config\UnsupportedDataTypeConfigException' with message 'Invalid data type in config basiccart.settings, found in filemodules/basiccart/config/install/basiccart.settings.yml : Unable to parse at line 24 (near "use_cart_table:0").' in   [error]
/srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/Config/FileStorage.php:99
Stack trace:
#0 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/Config/FileStorage.php(110): Drupal\Core\Config\FileStorage->read('basiccart.setti...')
#1 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/Config/ConfigInstaller.php(245): Drupal\Core\Config\FileStorage->readMultiple(Array)
#2 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/Config/ConfigInstaller.php(491): Drupal\Core\Config\ConfigInstaller->getConfigToCreate(Object(Drupal\Core\Config\FileStorage), '', '', Array)
#3 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/Config/ConfigInstaller.php(458): Drupal\Core\Config\ConfigInstaller->findDefaultConfigWithUnmetDependencies(Object(Drupal\Core\Config\FileStorage), Array, Array)
#4 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'basiccart')
#5 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141): Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'basiccart')
#6 /srv/bindings/8200a57c77074ee8a230fa79c7de965e/code/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#7 /opt/pantheon/drush-8/commands/core/drupal/environment.inc(131): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, true)
#8 /opt/pantheon/drush-8/commands/core/drupal/environment.inc(198): drush_module_install(Array)
#9 /opt/pantheon/drush-8/commands/pm/pm.drush.inc(1167): drush_module_enable(Array)
#10 [internal function]: drush_pm_enable('basiccart')
#11 /opt/pantheon/drush-8/includes/command.inc(366): call_user_func_array('drush_pm_enable', Array)
#12 /opt/pantheon/drush-8/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#13 [internal function]: drush_command('basiccart')
#14 /opt/pantheon/drush-8/includes/command.inc(185): call_user_func_array('drush_command', Array)
#15 /opt/pantheon/drush-8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#16 /opt/pantheon/drush-8/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#17 /opt/pantheon/drush-8/drush.php(12): drush_main()
```

**Comment by karthikeyan-manivasagam** [comment]
Fixed
